##str="THERE ARETW OWAYS OFCON STRUC TINGA SOFTW AREDE SIGNO NEWAY SYSTE MSYST EMSYS TEMSY STEMS YSTEM SYSTE MSYST EMSYS TEMSY LFWKI MJCLP SISWK HJOGL KMVGU RAGKM KMXMA MJCVX WUYLG GIISW ISTOM AKEIT SOSIM PLETH ATTHE REARE OBVIO USLYN ODEFI CIENC STEMS YSTEM SYSTE MSYST EMSYS TEMSY STEMS YSTEM SYSTE MSYST ALXAE YCXMF KMKBQ BDCLA EFLFW KIMJC GUZUG SKECZ GBWYM OACFV IESAN DTHEO THERW AYIST OMAKE ITSOC OMPLI CATED THATT HEREA EMSYS TEMSY STEMS YSTEM SYSTE MSYST EMSYS TEMSY STEMS YSTEM MQKYF WXTWM LAIDO YQBWF GKSDI ULQGV SYHJA VEFWB LAEFL FWKIM RENOO BVIOU SDEFI CIENC IESTH EFIRS TMETH ODISF ARMOR EDIFF SYSTE MSYST EMSYS TEMSY STEMS YSTEM SYSTE MSYST EMSYS TEMSY JCFHS NNGGN WPWDA VMQFA AXWFZ CXBVE LKWML AVGKY EDEMJ XHUXD ICULT STEMS AVYXL"           
# import math
# from functools import reduce
# str="VHVSSPVSQUCEMRVVSBVBQUCEBBVHVVSSURQGQUCEIBVSDUGRNVSICJNNQUCERVUAXSSR"
# sub="QUCE"
# dis=[]
# index=0
# for i in range(str.count(sub)):
#        index=str.find(sub,index)
#        dis.append(index)
#        index=index+len(sub)
# print(dis)
# l=len(dis)
# i=0
# pos=[]
# while i<l-1 :
#        j=i+1
#        while j<l :
#               pos.append(dis[j]-dis[i])
#               j=j+1
#        i=i+1       
# print(pos)   
# g=reduce(math.gcd,pos)
# print(g)  
# g =reduce(math.gcd,dis)
# print(g)


               
#        #1, 166, 236, 276 and 286.